/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author computador
 */
public class JF_Alumnos extends javax.swing.JFrame {

    /**
     * Creates new form JF_Alumnos
     */
    public JF_Alumnos() {
        initComponents();
         this.setTitle(" Gestion Alumnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_DatosAlumnos = new javax.swing.JPanel();
        jL_DNI = new javax.swing.JLabel();
        jL_Nombre = new javax.swing.JLabel();
        jL_Apellido1 = new javax.swing.JLabel();
        jL_Apellido2 = new javax.swing.JLabel();
        jL_Domicilio = new javax.swing.JLabel();
        jL_Ciudad = new javax.swing.JLabel();
        jL_Provincia = new javax.swing.JLabel();
        jL_CP = new javax.swing.JLabel();
        jL_Email = new javax.swing.JLabel();
        jL_Telefono = new javax.swing.JLabel();
        jT_DNI = new javax.swing.JTextField();
        jT_Nombre = new javax.swing.JTextField();
        jT_Apellido1 = new javax.swing.JTextField();
        jT_Apellido2 = new javax.swing.JTextField();
        jT_Domicilio = new javax.swing.JTextField();
        jT_Ciudad = new javax.swing.JTextField();
        jT_Provincia = new javax.swing.JTextField();
        jT_CP = new javax.swing.JTextField();
        jT_Email = new javax.swing.JTextField();
        jT_Telefono = new javax.swing.JTextField();
        jP_OpcionesAlumnos = new javax.swing.JPanel();
        Btn_InsertAlumnos = new javax.swing.JButton();
        Btn_ModificarAlumnos = new javax.swing.JButton();
        Btn_EliminarAlumnos = new javax.swing.JButton();
        Btn_BuscarAlumnos = new javax.swing.JButton();
        Btn_MenuAlumnos = new javax.swing.JButton();
        jP_DetallesAlumnos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_TablaAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_DatosAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jL_DNI.setText("DNI:");

        jL_Nombre.setText("Nombre:");

        jL_Apellido1.setText("Apellido 1:");

        jL_Apellido2.setText("Apellido 2:");

        jL_Domicilio.setText("Domicilio:");

        jL_Ciudad.setText("Ciudad:");

        jL_Provincia.setText("Provincia:");

        jL_CP.setText("CP:");

        jL_Email.setText("Email:");

        jL_Telefono.setText("Telefono:");

        jT_Apellido2.setToolTipText("");

        javax.swing.GroupLayout jP_DatosAlumnosLayout = new javax.swing.GroupLayout(jP_DatosAlumnos);
        jP_DatosAlumnos.setLayout(jP_DatosAlumnosLayout);
        jP_DatosAlumnosLayout.setHorizontalGroup(
            jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jP_DatosAlumnosLayout.createSequentialGroup()
                            .addComponent(jL_Apellido2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jT_Apellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGroup(jP_DatosAlumnosLayout.createSequentialGroup()
                            .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jL_DNI)
                                .addComponent(jL_Nombre)
                                .addComponent(jL_Apellido1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jT_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(jT_Apellido1)
                                .addComponent(jT_DNI)))
                        .addGroup(jP_DatosAlumnosLayout.createSequentialGroup()
                            .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jL_CP)
                                .addComponent(jL_Provincia))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jT_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jP_DatosAlumnosLayout.createSequentialGroup()
                        .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Ciudad)
                            .addComponent(jL_Domicilio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_DatosAlumnosLayout.createSequentialGroup()
                        .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Email)
                            .addComponent(jL_Telefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jP_DatosAlumnosLayout.setVerticalGroup(
            jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_DNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Nombre)
                    .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Apellido1)
                    .addComponent(jT_Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Apellido2)
                    .addComponent(jT_Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Domicilio)
                    .addComponent(jT_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Ciudad)
                    .addComponent(jT_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Provincia)
                    .addComponent(jT_Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_CP)
                    .addComponent(jT_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Email)
                    .addComponent(jT_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Telefono)
                    .addComponent(jT_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_OpcionesAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        Btn_InsertAlumnos.setForeground(new java.awt.Color(0, 128, 0));
        Btn_InsertAlumnos.setText("Insertar");

        Btn_ModificarAlumnos.setForeground(new java.awt.Color(0, 0, 255));
        Btn_ModificarAlumnos.setText("Modificar");

        Btn_EliminarAlumnos.setForeground(new java.awt.Color(255, 0, 0));
        Btn_EliminarAlumnos.setText("Eliminar");
        Btn_EliminarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarAlumnosActionPerformed(evt);
            }
        });

        Btn_BuscarAlumnos.setForeground(new java.awt.Color(255, 128, 0));
        Btn_BuscarAlumnos.setText("Buscar");

        Btn_MenuAlumnos.setForeground(new java.awt.Color(255, 255, 0));
        Btn_MenuAlumnos.setText("Menu");
        Btn_MenuAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_OpcionesAlumnosLayout = new javax.swing.GroupLayout(jP_OpcionesAlumnos);
        jP_OpcionesAlumnos.setLayout(jP_OpcionesAlumnosLayout);
        jP_OpcionesAlumnosLayout.setHorizontalGroup(
            jP_OpcionesAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcionesAlumnosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jP_OpcionesAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_ModificarAlumnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_OpcionesAlumnosLayout.createSequentialGroup()
                        .addGroup(jP_OpcionesAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_MenuAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_BuscarAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_InsertAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_EliminarAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(27, 27, 27))
        );
        jP_OpcionesAlumnosLayout.setVerticalGroup(
            jP_OpcionesAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcionesAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_InsertAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_ModificarAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_EliminarAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_BuscarAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_MenuAlumnos))
        );

        jP_DetallesAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        jT_TablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido 1", "Apellido 2", "Domicilio", "Ciudad", "Provincia", "CP", "Email", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jT_TablaAlumnos);

        javax.swing.GroupLayout jP_DetallesAlumnosLayout = new javax.swing.GroupLayout(jP_DetallesAlumnos);
        jP_DetallesAlumnos.setLayout(jP_DetallesAlumnosLayout);
        jP_DetallesAlumnosLayout.setHorizontalGroup(
            jP_DetallesAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DetallesAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_DetallesAlumnosLayout.setVerticalGroup(
            jP_DetallesAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DetallesAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_DatosAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP_OpcionesAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jP_DetallesAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_DatosAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jP_OpcionesAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP_DetallesAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EliminarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EliminarAlumnosActionPerformed

    private void Btn_MenuAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuAlumnosActionPerformed
        // TODO add your handling code here:
                Menu obj = new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_MenuAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BuscarAlumnos;
    private javax.swing.JButton Btn_EliminarAlumnos;
    private javax.swing.JButton Btn_InsertAlumnos;
    private javax.swing.JButton Btn_MenuAlumnos;
    private javax.swing.JButton Btn_ModificarAlumnos;
    private javax.swing.JLabel jL_Apellido1;
    private javax.swing.JLabel jL_Apellido2;
    private javax.swing.JLabel jL_CP;
    private javax.swing.JLabel jL_Ciudad;
    private javax.swing.JLabel jL_DNI;
    private javax.swing.JLabel jL_Domicilio;
    private javax.swing.JLabel jL_Email;
    private javax.swing.JLabel jL_Nombre;
    private javax.swing.JLabel jL_Provincia;
    private javax.swing.JLabel jL_Telefono;
    private javax.swing.JPanel jP_DatosAlumnos;
    private javax.swing.JPanel jP_DetallesAlumnos;
    private javax.swing.JPanel jP_OpcionesAlumnos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Apellido1;
    private javax.swing.JTextField jT_Apellido2;
    private javax.swing.JTextField jT_CP;
    private javax.swing.JTextField jT_Ciudad;
    private javax.swing.JTextField jT_DNI;
    private javax.swing.JTextField jT_Domicilio;
    private javax.swing.JTextField jT_Email;
    private javax.swing.JTextField jT_Nombre;
    private javax.swing.JTextField jT_Provincia;
    private javax.swing.JTable jT_TablaAlumnos;
    private javax.swing.JTextField jT_Telefono;
    // End of variables declaration//GEN-END:variables
}
