package Views;

import javax.swing.table.DefaultTableModel;
import Controladores.CursosC;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class JF_Cursos extends javax.swing.JFrame {

    public JF_Cursos() {
        initComponents();
        this.setTitle(" Gestion Cursos ");
        LimpiarTabla();
        LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jp_Detalles = new javax.swing.JPanel();
        JS_TablaCursos = new javax.swing.JScrollPane();
        tbl_TablaCursos = new javax.swing.JTable();
        Jp_datos = new javax.swing.JPanel();
        jl_Curso = new javax.swing.JLabel();
        jl_Denominacion = new javax.swing.JLabel();
        jl_HorasLectivas = new javax.swing.JLabel();
        jl_Modalidad = new javax.swing.JLabel();
        Jl_Objetivos = new javax.swing.JLabel();
        Jl_Contenidos = new javax.swing.JLabel();
        JT_Curso = new javax.swing.JTextField();
        JT_Denominacion = new javax.swing.JTextField();
        JT_Horas = new javax.swing.JTextField();
        JT_Modalidad = new javax.swing.JTextField();
        JT_Objetivos = new javax.swing.JTextField();
        Jt_Contenidos = new javax.swing.JTextField();
        Jp_Opciones = new javax.swing.JPanel();
        Btn_InsertCurso = new javax.swing.JButton();
        Btn_ModificarCurso = new javax.swing.JButton();
        Btn_EliminarCurso = new javax.swing.JButton();
        Btn_BuscarCurso = new javax.swing.JButton();
        Btn_MenuCursos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jp_Detalles.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));
        Jp_Detalles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl_TablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "N. Curso", "Denominacion", "Horas lectivas", "Modalidad", "Objetivos", "Contenidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_TablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TablaCursosMouseClicked(evt);
            }
        });
        JS_TablaCursos.setViewportView(tbl_TablaCursos);
        if (tbl_TablaCursos.getColumnModel().getColumnCount() > 0) {
            tbl_TablaCursos.getColumnModel().getColumn(0).setResizable(false);
            tbl_TablaCursos.getColumnModel().getColumn(0).setPreferredWidth(1);
            tbl_TablaCursos.getColumnModel().getColumn(1).setResizable(false);
            tbl_TablaCursos.getColumnModel().getColumn(1).setPreferredWidth(40);
            tbl_TablaCursos.getColumnModel().getColumn(2).setResizable(false);
            tbl_TablaCursos.getColumnModel().getColumn(2).setPreferredWidth(40);
            tbl_TablaCursos.getColumnModel().getColumn(3).setResizable(false);
            tbl_TablaCursos.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbl_TablaCursos.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        javax.swing.GroupLayout Jp_DetallesLayout = new javax.swing.GroupLayout(Jp_Detalles);
        Jp_Detalles.setLayout(Jp_DetallesLayout);
        Jp_DetallesLayout.setHorizontalGroup(
            Jp_DetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_DetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JS_TablaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        Jp_DetallesLayout.setVerticalGroup(
            Jp_DetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_DetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JS_TablaCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        Jp_datos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        Jp_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jl_Curso.setText("N. Curso:");

        jl_Denominacion.setText("Denominacion:");

        jl_HorasLectivas.setText("Horas lectivas:");

        jl_Modalidad.setText("Modalidad:");

        Jl_Objetivos.setText("Objetivos:");

        Jl_Contenidos.setText("Contenidos:");

        JT_Curso.setEnabled(false);

        javax.swing.GroupLayout Jp_datosLayout = new javax.swing.GroupLayout(Jp_datos);
        Jp_datos.setLayout(Jp_datosLayout);
        Jp_datosLayout.setHorizontalGroup(
            Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jp_datosLayout.createSequentialGroup()
                        .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_Denominacion)
                            .addComponent(jl_Curso))
                        .addGap(18, 18, 18)
                        .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Denominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jp_datosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_Modalidad)
                            .addComponent(jl_HorasLectivas)
                            .addComponent(Jl_Objetivos)
                            .addComponent(Jl_Contenidos))
                        .addGap(18, 18, 18)
                        .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jt_Contenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Objetivos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Modalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        Jp_datosLayout.setVerticalGroup(
            Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Curso)
                    .addComponent(JT_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Denominacion)
                    .addComponent(JT_Denominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_HorasLectivas)
                    .addComponent(JT_Horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Modalidad)
                    .addComponent(JT_Modalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_Objetivos)
                    .addComponent(JT_Objetivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_Contenidos)
                    .addComponent(Jt_Contenidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jp_Opciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        Jp_Opciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Btn_InsertCurso.setForeground(new java.awt.Color(0, 128, 0));
        Btn_InsertCurso.setText("Insertar");
        Btn_InsertCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InsertCursoActionPerformed(evt);
            }
        });

        Btn_ModificarCurso.setForeground(new java.awt.Color(0, 0, 255));
        Btn_ModificarCurso.setText("Modificar");

        Btn_EliminarCurso.setForeground(new java.awt.Color(255, 0, 0));
        Btn_EliminarCurso.setText("Eliminar");
        Btn_EliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarCursoActionPerformed(evt);
            }
        });

        Btn_BuscarCurso.setForeground(new java.awt.Color(255, 128, 0));
        Btn_BuscarCurso.setText("Buscar");

        Btn_MenuCursos.setForeground(new java.awt.Color(255, 255, 0));
        Btn_MenuCursos.setText("Menu");
        Btn_MenuCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jp_OpcionesLayout = new javax.swing.GroupLayout(Jp_Opciones);
        Jp_Opciones.setLayout(Jp_OpcionesLayout);
        Jp_OpcionesLayout.setHorizontalGroup(
            Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_OpcionesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_ModificarCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_OpcionesLayout.createSequentialGroup()
                        .addGroup(Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_MenuCursos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_BuscarCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_InsertCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_EliminarCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(27, 27, 27))
        );
        Jp_OpcionesLayout.setVerticalGroup(
            Jp_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_OpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_InsertCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_ModificarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_EliminarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_BuscarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_MenuCursos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Jp_Detalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Jp_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jp_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jp_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Jp_Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Jp_Detalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EliminarCursoActionPerformed

    private void Btn_MenuCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuCursosActionPerformed
        // TODO add your handling code here:
        Menu obj = new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_MenuCursosActionPerformed

    private void Btn_InsertCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InsertCursoActionPerformed

        System.out.println("Boton de insertar");
        String DenominacionC;
        int HorasC;
        String ModalidadC;
        String ObjetivosC;
        String ContenidosC;
        int guardado;

        DenominacionC = JT_Denominacion.getText().toString();
        HorasC = Integer.parseInt(JT_Horas.getText().toString());
        ModalidadC = JT_Modalidad.getText().toString();
        ObjetivosC = JT_Objetivos.getText().toString();
        ContenidosC = Jt_Contenidos.getText().toString();

        CursosC regCurso = new CursosC();

        try {
            guardado = regCurso.RegistrarCurso(DenominacionC, HorasC, ModalidadC, ObjetivosC, ContenidosC);

            if (guardado == 0) {
                JOptionPane.showMessageDialog(null, "No se guardo el registro");
            } else {
                JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JF_Cursos.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimpiarTxt();
        LimpiarTabla();
        LlenarTabla();
    }//GEN-LAST:event_Btn_InsertCursoActionPerformed

    private void tbl_TablaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TablaCursosMouseClicked
        if (evt.getClickCount() == 2) {
            MostrarTabla();
        }
    }//GEN-LAST:event_tbl_TablaCursosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Cursos().setVisible(true);
            }
        });
    }

    public void LimpiarTabla() {
        for (int i = 0; i < tbl_TablaCursos.getRowCount(); i++) {
            DefaultTableModel modelo = (DefaultTableModel) tbl_TablaCursos.getModel();
            modelo.removeRow(i);
            i -= 1;
        }
    }

    public void LlenarTabla() {
        Object[][] curs = null;

        CursosC cur = new CursosC();

        curs = cur.CargarTablaCursos();

        DefaultTableModel modelo2 = (DefaultTableModel) tbl_TablaCursos.getModel();

        for (int i = 0; i < curs.length; i++) {
            modelo2.addRow(curs[i]);
        }

        tbl_TablaCursos.setModel(modelo2);
    }

    public void LimpiarTxt() {
        JT_Curso.enable();
        JT_Denominacion.setText("");
        JT_Horas.setText("");
        JT_Modalidad.setText("");
        JT_Objetivos.setText("");
        Jt_Contenidos.setText("");
    }

    public void MostrarTabla() {
        int HorasC = 0;
        int NumCursoC = 0;
        DefaultTableModel tc = (DefaultTableModel) tbl_TablaCursos.getModel();

        String NumCur = String.valueOf(tc.getValueAt(tbl_TablaCursos.getSelectedRow(), 0));
        String DenomCur = String.valueOf(tc.getValueAt(tbl_TablaCursos.getSelectedRow(), 1));
        String HoraCur = String.valueOf(tc.getValueAt(tbl_TablaCursos.getSelectedRow(), 2));
        String ModaCur = String.valueOf(tc.getValueAt(tbl_TablaCursos.getSelectedRow(), 3));
        String ObjeCur = String.valueOf(tc.getValueAt(tbl_TablaCursos.getSelectedRow(), 4));
        String ContenCur = String.valueOf(tc.getValueAt(tbl_TablaCursos.getSelectedRow(), 5));

        NumCursoC = Integer.parseInt(NumCur);
        HorasC = Integer.parseInt(HoraCur);
        
        String NumeroCurso = Integer.toString(NumCursoC);
        String HorasCurso = Integer.toString(HorasC);
        
        JT_Curso.setText(NumeroCurso);
        JT_Denominacion.setText(DenomCur);
        JT_Horas.setText(HorasCurso);
        JT_Modalidad.setText(ModaCur);
        JT_Objetivos.setText(ObjeCur);
        Jt_Contenidos.setText(ContenCur);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BuscarCurso;
    private javax.swing.JButton Btn_EliminarCurso;
    private javax.swing.JButton Btn_InsertCurso;
    private javax.swing.JButton Btn_MenuCursos;
    private javax.swing.JButton Btn_ModificarCurso;
    private javax.swing.JScrollPane JS_TablaCursos;
    private javax.swing.JTextField JT_Curso;
    private javax.swing.JTextField JT_Denominacion;
    private javax.swing.JTextField JT_Horas;
    private javax.swing.JTextField JT_Modalidad;
    private javax.swing.JTextField JT_Objetivos;
    private javax.swing.JLabel Jl_Contenidos;
    private javax.swing.JLabel Jl_Objetivos;
    private javax.swing.JPanel Jp_Detalles;
    private javax.swing.JPanel Jp_Opciones;
    private javax.swing.JPanel Jp_datos;
    private javax.swing.JTextField Jt_Contenidos;
    private javax.swing.JLabel jl_Curso;
    private javax.swing.JLabel jl_Denominacion;
    private javax.swing.JLabel jl_HorasLectivas;
    private javax.swing.JLabel jl_Modalidad;
    private javax.swing.JTable tbl_TablaCursos;
    // End of variables declaration//GEN-END:variables
}
