/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author computador
 */
public class JF_Grupos extends javax.swing.JFrame {

    /**
     * Creates new form JF_Grupos
     */
    public JF_Grupos() {
        initComponents();
         this.setTitle(" Gestion Grupos ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_DatosGrupos = new javax.swing.JPanel();
        jL_NCurso = new javax.swing.JLabel();
        jL_NGrupo = new javax.swing.JLabel();
        jL_FechaINi = new javax.swing.JLabel();
        jL_FechaFin = new javax.swing.JLabel();
        jL_Horario = new javax.swing.JLabel();
        jL_DiasImp = new javax.swing.JLabel();
        jL_LugarImp = new javax.swing.JLabel();
        jL_Profesor = new javax.swing.JLabel();
        jT_NCurso = new javax.swing.JTextField();
        jT_NGrupo = new javax.swing.JTextField();
        jT_FechaIni = new javax.swing.JTextField();
        jT_FechaFin = new javax.swing.JTextField();
        jT_Horario = new javax.swing.JTextField();
        jT_DiasImp = new javax.swing.JTextField();
        jT_LugarImp = new javax.swing.JTextField();
        jT_Profesor = new javax.swing.JTextField();
        jP_OpcionesGrupos = new javax.swing.JPanel();
        Btn_InsertGrupos = new javax.swing.JButton();
        Btn_ModificarGrupos = new javax.swing.JButton();
        Btn_EliminarGrupos = new javax.swing.JButton();
        Btn_BuscarGrupos = new javax.swing.JButton();
        Btn_MenuGrupos = new javax.swing.JButton();
        jP_DetallesGrupos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_TablaGrupos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_DatosGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jL_NCurso.setText("N. Curso:");

        jL_NGrupo.setText("N. Grupo:");

        jL_FechaINi.setText("Fecha inicio:");

        jL_FechaFin.setText("Fecha Fin:");

        jL_Horario.setText("Horario:");

        jL_DiasImp.setText("Dias imparticion:");

        jL_LugarImp.setText("Lugar Imparticion:");

        jL_Profesor.setText("Profesor:");

        javax.swing.GroupLayout jP_DatosGruposLayout = new javax.swing.GroupLayout(jP_DatosGrupos);
        jP_DatosGrupos.setLayout(jP_DatosGruposLayout);
        jP_DatosGruposLayout.setHorizontalGroup(
            jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_LugarImp)
                    .addComponent(jL_DiasImp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Horario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_FechaFin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_FechaINi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_NGrupo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_NCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Profesor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_DatosGruposLayout.createSequentialGroup()
                        .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jT_NGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jT_NCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_FechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(jT_FechaFin)
                                .addComponent(jT_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jT_DiasImp, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_LugarImp))
                        .addGap(232, 232, 232))
                    .addGroup(jP_DatosGruposLayout.createSequentialGroup()
                        .addComponent(jT_Profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jP_DatosGruposLayout.setVerticalGroup(
            jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosGruposLayout.createSequentialGroup()
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_NCurso)
                    .addComponent(jT_NCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_NGrupo)
                    .addComponent(jT_NGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_FechaINi)
                    .addComponent(jT_FechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_FechaFin)
                    .addComponent(jT_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Horario)
                    .addComponent(jT_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_DiasImp)
                    .addComponent(jT_DiasImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_LugarImp)
                    .addComponent(jT_LugarImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_DatosGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Profesor)
                    .addComponent(jT_Profesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jP_OpcionesGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        Btn_InsertGrupos.setForeground(new java.awt.Color(0, 128, 0));
        Btn_InsertGrupos.setText("Insertar");

        Btn_ModificarGrupos.setForeground(new java.awt.Color(0, 0, 255));
        Btn_ModificarGrupos.setText("Modificar");

        Btn_EliminarGrupos.setForeground(new java.awt.Color(255, 0, 0));
        Btn_EliminarGrupos.setText("Eliminar");
        Btn_EliminarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarGruposActionPerformed(evt);
            }
        });

        Btn_BuscarGrupos.setForeground(new java.awt.Color(255, 128, 0));
        Btn_BuscarGrupos.setText("Buscar");

        Btn_MenuGrupos.setForeground(new java.awt.Color(255, 255, 0));
        Btn_MenuGrupos.setText("Menu");
        Btn_MenuGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuGruposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_OpcionesGruposLayout = new javax.swing.GroupLayout(jP_OpcionesGrupos);
        jP_OpcionesGrupos.setLayout(jP_OpcionesGruposLayout);
        jP_OpcionesGruposLayout.setHorizontalGroup(
            jP_OpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_OpcionesGruposLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jP_OpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_ModificarGrupos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_OpcionesGruposLayout.createSequentialGroup()
                        .addGroup(jP_OpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_BuscarGrupos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_InsertGrupos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_EliminarGrupos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_MenuGrupos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(27, 27, 27))
        );
        jP_OpcionesGruposLayout.setVerticalGroup(
            jP_OpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcionesGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_InsertGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_ModificarGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_EliminarGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_BuscarGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_MenuGrupos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_DetallesGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        jT_TablaGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N. Curso", "N. Grupo", "Fecha Inicio", "Fecha Fin", "Horario", "Dia imparticion", "Lugar Imparticion", "Profesor"
            }
        ));
        jScrollPane1.setViewportView(jT_TablaGrupos);
        if (jT_TablaGrupos.getColumnModel().getColumnCount() > 0) {
            jT_TablaGrupos.getColumnModel().getColumn(0).setPreferredWidth(1);
            jT_TablaGrupos.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        javax.swing.GroupLayout jP_DetallesGruposLayout = new javax.swing.GroupLayout(jP_DetallesGrupos);
        jP_DetallesGrupos.setLayout(jP_DetallesGruposLayout);
        jP_DetallesGruposLayout.setHorizontalGroup(
            jP_DetallesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DetallesGruposLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jP_DetallesGruposLayout.setVerticalGroup(
            jP_DetallesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DetallesGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_DetallesGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_DatosGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(jP_OpcionesGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_DatosGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jP_OpcionesGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP_DetallesGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EliminarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EliminarGruposActionPerformed

    private void Btn_MenuGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuGruposActionPerformed
        // TODO add your handling code here:
                Menu obj = new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_MenuGruposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Grupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BuscarGrupos;
    private javax.swing.JButton Btn_EliminarGrupos;
    private javax.swing.JButton Btn_InsertGrupos;
    private javax.swing.JButton Btn_MenuGrupos;
    private javax.swing.JButton Btn_ModificarGrupos;
    private javax.swing.JLabel jL_DiasImp;
    private javax.swing.JLabel jL_FechaFin;
    private javax.swing.JLabel jL_FechaINi;
    private javax.swing.JLabel jL_Horario;
    private javax.swing.JLabel jL_LugarImp;
    private javax.swing.JLabel jL_NCurso;
    private javax.swing.JLabel jL_NGrupo;
    private javax.swing.JLabel jL_Profesor;
    private javax.swing.JPanel jP_DatosGrupos;
    private javax.swing.JPanel jP_DetallesGrupos;
    private javax.swing.JPanel jP_OpcionesGrupos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_DiasImp;
    private javax.swing.JTextField jT_FechaFin;
    private javax.swing.JTextField jT_FechaIni;
    private javax.swing.JTextField jT_Horario;
    private javax.swing.JTextField jT_LugarImp;
    private javax.swing.JTextField jT_NCurso;
    private javax.swing.JTextField jT_NGrupo;
    private javax.swing.JTextField jT_Profesor;
    private javax.swing.JTable jT_TablaGrupos;
    // End of variables declaration//GEN-END:variables
}
