/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controladores.ProfesoresC;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class JF_Profesores extends javax.swing.JFrame {

    public JF_Profesores() {
        initComponents();
        this.setTitle(" Gestion Profesores ");
        LimpiarTabla();
        LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_DatosProfesores = new javax.swing.JPanel();
        jL_DNI = new javax.swing.JLabel();
        jL_NISS = new javax.swing.JLabel();
        jL_Nombre = new javax.swing.JLabel();
        jL_Apellido1 = new javax.swing.JLabel();
        jL_Apellido2 = new javax.swing.JLabel();
        jL_Domicilio = new javax.swing.JLabel();
        jL_Ciudad = new javax.swing.JLabel();
        jL_Provincia = new javax.swing.JLabel();
        jL_CP = new javax.swing.JLabel();
        jL_Email = new javax.swing.JLabel();
        jL_Telefono = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_DNI = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_NISS = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_Nombre = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_Apellido1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jT_Apellido2 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jT_Domicilio = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jT_Ciudad = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jT_Provincia = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jT_CP = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jT_Email = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jT_Telefono = new javax.swing.JTextPane();
        jP_OpcionesProfesores = new javax.swing.JPanel();
        jB_InsertProfesores = new javax.swing.JButton();
        jB_ModificarProfesores = new javax.swing.JButton();
        jB_EliminarProfesores = new javax.swing.JButton();
        jB_BuscarProfesores = new javax.swing.JButton();
        Btn_MenuProfesores = new javax.swing.JButton();
        jP_DetallesProfesores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_TablaProfesores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_DatosProfesores.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jL_DNI.setText("DNI:");

        jL_NISS.setText("NISS:");

        jL_Nombre.setText("Nombre:");

        jL_Apellido1.setText("Apellido1:");

        jL_Apellido2.setText("Apellido 2:");

        jL_Domicilio.setText("Domicilio:");

        jL_Ciudad.setText("Ciudad:");

        jL_Provincia.setText("Provincia:");

        jL_CP.setText("CP:");

        jL_Email.setText("Email:");

        jL_Telefono.setText("Telefono:");

        jScrollPane2.setViewportView(jT_DNI);

        jScrollPane3.setViewportView(jT_NISS);

        jScrollPane4.setViewportView(jT_Nombre);

        jScrollPane5.setViewportView(jT_Apellido1);

        jScrollPane6.setViewportView(jT_Apellido2);

        jScrollPane7.setViewportView(jT_Domicilio);

        jScrollPane8.setViewportView(jT_Ciudad);

        jScrollPane9.setViewportView(jT_Provincia);

        jScrollPane10.setViewportView(jT_CP);

        jScrollPane11.setViewportView(jT_Email);

        jScrollPane12.setViewportView(jT_Telefono);

        javax.swing.GroupLayout jP_DatosProfesoresLayout = new javax.swing.GroupLayout(jP_DatosProfesores);
        jP_DatosProfesores.setLayout(jP_DatosProfesoresLayout);
        jP_DatosProfesoresLayout.setHorizontalGroup(
            jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                        .addComponent(jL_Apellido2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_DNI)
                            .addComponent(jL_Apellido1)
                            .addComponent(jL_NISS)
                            .addComponent(jL_Nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)))
                    .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Ciudad)
                            .addComponent(jL_Domicilio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_CP)
                            .addComponent(jL_Provincia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Email)
                            .addComponent(jL_Telefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11)
                            .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jP_DatosProfesoresLayout.setVerticalGroup(
            jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_DNI)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_NISS)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Nombre)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Apellido1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Apellido2)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Domicilio)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Ciudad)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Provincia)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_CP)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Email)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_DatosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Telefono)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jP_OpcionesProfesores.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jP_OpcionesProfesores.setToolTipText("Opciones");

        jB_InsertProfesores.setForeground(new java.awt.Color(0, 128, 0));
        jB_InsertProfesores.setText("Insertar");

        jB_ModificarProfesores.setForeground(new java.awt.Color(0, 0, 255));
        jB_ModificarProfesores.setText("Modificar");

        jB_EliminarProfesores.setForeground(new java.awt.Color(255, 0, 0));
        jB_EliminarProfesores.setText("Eliminar");
        jB_EliminarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EliminarProfesoresActionPerformed(evt);
            }
        });

        jB_BuscarProfesores.setForeground(new java.awt.Color(255, 128, 0));
        jB_BuscarProfesores.setText("Buscar");

        Btn_MenuProfesores.setForeground(new java.awt.Color(255, 255, 0));
        Btn_MenuProfesores.setText("Menu");
        Btn_MenuProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuProfesoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_OpcionesProfesoresLayout = new javax.swing.GroupLayout(jP_OpcionesProfesores);
        jP_OpcionesProfesores.setLayout(jP_OpcionesProfesoresLayout);
        jP_OpcionesProfesoresLayout.setHorizontalGroup(
            jP_OpcionesProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcionesProfesoresLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jP_OpcionesProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_ModificarProfesores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_OpcionesProfesoresLayout.createSequentialGroup()
                        .addGroup(jP_OpcionesProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_MenuProfesores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB_BuscarProfesores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB_InsertProfesores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB_EliminarProfesores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(27, 27, 27))
        );
        jP_OpcionesProfesoresLayout.setVerticalGroup(
            jP_OpcionesProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcionesProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_InsertProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_ModificarProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_EliminarProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_BuscarProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_MenuProfesores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_DetallesProfesores.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jT_TablaProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "NISS", "Nombre", "Apellido 1", "Apellido 2", "Domicilio", "Ciudad", "Provincia", "CP", "Email", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jT_TablaProfesores);

        javax.swing.GroupLayout jP_DetallesProfesoresLayout = new javax.swing.GroupLayout(jP_DetallesProfesores);
        jP_DetallesProfesores.setLayout(jP_DetallesProfesoresLayout);
        jP_DetallesProfesoresLayout.setHorizontalGroup(
            jP_DetallesProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DetallesProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jP_DetallesProfesoresLayout.setVerticalGroup(
            jP_DetallesProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DetallesProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jP_DatosProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jP_OpcionesProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addComponent(jP_DetallesProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jP_DatosProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jP_OpcionesProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_DetallesProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_EliminarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EliminarProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_EliminarProfesoresActionPerformed

    private void Btn_MenuProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuProfesoresActionPerformed
        // TODO add your handling code here:
        Menu obj = new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_MenuProfesoresActionPerformed

    private void Btn_InsertCursoActionPerformed(java.awt.event.ActionEvent evt, String DNIC, String NISSC, String NombreC, String Apellido1C, String Apellido2C, String DomicilioC, String CiudadC, String ProvinciaC, String CPC, String EmailC, String TelefonoC) {

        System.out.println("Boton de insertar");
        char DNI;
        char NISS;
        char Nombre;
        char Apellido1;
        char Apellido2;
        char Domicilio;
        char Ciudad;
        char Provincia;
        char CP;
        char Email;
        char Telefono;

        char guardado;

        DNIC = jT_DNI.getText().toString();
        NISSC = jT_NISS.getText().toString();
        NombreC = jT_Nombre.getText().toString();
        Apellido1C = jT_Apellido1.getText().toString();
        Apellido2C = jT_Apellido2.getText().toString();
        DomicilioC = jT_Domicilio.getText().toString();
        CiudadC = jT_Ciudad.getText().toString();
        ProvinciaC = jT_Provincia.getText().toString();
        CPC = jT_CP.getText().toString();
        EmailC = jT_Email.getText().toString();
        TelefonoC = jT_Telefono.getText().toString();

        ProfesoresC regProfesores = new ProfesoresC();

        try {
            guardado = regProfesores.RegistrarProfesores(DNIC, NISSC, NombreC, Apellido1C, Apellido2C, DomicilioC, CiudadC, ProvinciaC, CPC, EmailC, TelefonoC);

            if (guardado == 0) {
                JOptionPane.showMessageDialog(null, "No se guardo el registro");
            } else {
                JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JF_Profesores.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimpiarTxt();
        LimpiarTabla();
        LlenarTabla();
    }

    private void tbl_TablaProfesoresMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            MostrarTabla();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Profesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Profesores().setVisible(true);
            }
        });
    }

    private void LimpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jT_TablaProfesores.getModel();
        modelo.setRowCount(0);
    }

    public void LlenarTabla() {
        for (char i = 0; i < jT_TablaProfesores.getRowCount(); i++) {
            DefaultTableModel modelo = (DefaultTableModel) jT_TablaProfesores.getModel();
            modelo.removeRow(i);
            i -= 1;
        }
    }

    public void LimpiarTxt() {
        jT_DNI.setText("");
        jT_NISS.setText("");
        jT_Nombre.setText("");
        jT_Apellido1.setText("");
        jT_Apellido2.setText("");
        jT_Domicilio.setText("");
        jT_Ciudad.setText("");
        jT_Provincia.setText("");
        jT_CP.setText("");
        jT_Email.setText("");
        jT_Telefono.setText("");
    }

    public void MostrarTabla() {
        int filaSeleccionada = jT_TablaProfesores.getSelectedRow();
        if (filaSeleccionada >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jT_TablaProfesores.getModel();
            jT_DNI.setText(modelo.getValueAt(filaSeleccionada, 0) != null ? modelo.getValueAt(filaSeleccionada, 0).toString() : "");
            jT_NISS.setText(modelo.getValueAt(filaSeleccionada, 1) != null ? modelo.getValueAt(filaSeleccionada, 1).toString() : "");
            jT_Nombre.setText(modelo.getValueAt(filaSeleccionada, 2) != null ? modelo.getValueAt(filaSeleccionada, 2).toString() : "");
            jT_Apellido1.setText(modelo.getValueAt(filaSeleccionada, 3) != null ? modelo.getValueAt(filaSeleccionada, 3).toString() : "");
            jT_Apellido2.setText(modelo.getValueAt(filaSeleccionada, 4) != null ? modelo.getValueAt(filaSeleccionada, 4).toString() : "");
            jT_Domicilio.setText(modelo.getValueAt(filaSeleccionada, 5) != null ? modelo.getValueAt(filaSeleccionada, 5).toString() : "");
            jT_Ciudad.setText(modelo.getValueAt(filaSeleccionada, 6) != null ? modelo.getValueAt(filaSeleccionada, 6).toString() : "");
            jT_Provincia.setText(modelo.getValueAt(filaSeleccionada, 7) != null ? modelo.getValueAt(filaSeleccionada, 7).toString() : "");
            jT_CP.setText(modelo.getValueAt(filaSeleccionada, 8) != null ? modelo.getValueAt(filaSeleccionada, 8).toString() : "");
            jT_Email.setText(modelo.getValueAt(filaSeleccionada, 9) != null ? modelo.getValueAt(filaSeleccionada, 9).toString() : "");
            jT_Telefono.setText(modelo.getValueAt(filaSeleccionada, 10) != null ? modelo.getValueAt(filaSeleccionada, 10).toString() : "");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_MenuProfesores;
    private javax.swing.JButton jB_BuscarProfesores;
    private javax.swing.JButton jB_EliminarProfesores;
    private javax.swing.JButton jB_InsertProfesores;
    private javax.swing.JButton jB_ModificarProfesores;
    private javax.swing.JLabel jL_Apellido1;
    private javax.swing.JLabel jL_Apellido2;
    private javax.swing.JLabel jL_CP;
    private javax.swing.JLabel jL_Ciudad;
    private javax.swing.JLabel jL_DNI;
    private javax.swing.JLabel jL_Domicilio;
    private javax.swing.JLabel jL_Email;
    private javax.swing.JLabel jL_NISS;
    private javax.swing.JLabel jL_Nombre;
    private javax.swing.JLabel jL_Provincia;
    private javax.swing.JLabel jL_Telefono;
    private javax.swing.JPanel jP_DatosProfesores;
    private javax.swing.JPanel jP_DetallesProfesores;
    private javax.swing.JPanel jP_OpcionesProfesores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jT_Apellido1;
    private javax.swing.JTextPane jT_Apellido2;
    private javax.swing.JTextPane jT_CP;
    private javax.swing.JTextPane jT_Ciudad;
    private javax.swing.JTextPane jT_DNI;
    private javax.swing.JTextPane jT_Domicilio;
    private javax.swing.JTextPane jT_Email;
    private javax.swing.JTextPane jT_NISS;
    private javax.swing.JTextPane jT_Nombre;
    private javax.swing.JTextPane jT_Provincia;
    private javax.swing.JTable jT_TablaProfesores;
    private javax.swing.JTextPane jT_Telefono;
    // End of variables declaration//GEN-END:variables
}
