/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author computador
 */
public class JF_Participantes extends javax.swing.JFrame {

    /**
     * Creates new form JF_Participantes
     */
    public JF_Participantes() {
        initComponents();
         this.setTitle(" Gestion Participantes ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_DatosParticipantes = new javax.swing.JPanel();
        jL_NCurso = new javax.swing.JLabel();
        jL_NGrupo = new javax.swing.JLabel();
        jL_Alumno = new javax.swing.JLabel();
        jL_Apto = new javax.swing.JLabel();
        jT_NCurso = new javax.swing.JTextField();
        jT_NGrupo = new javax.swing.JTextField();
        jT_Alumno = new javax.swing.JTextField();
        jC_Apto = new javax.swing.JCheckBox();
        jP_OpcionesParticipantes = new javax.swing.JPanel();
        Btn_InsertParticipantes = new javax.swing.JButton();
        Btn_ModificarParticipantes = new javax.swing.JButton();
        Btn_EliminarParticipantes = new javax.swing.JButton();
        Btn_BuscarParticipantes = new javax.swing.JButton();
        Btn_MenuParticipantes = new javax.swing.JButton();
        jP_DetallesParticipantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaParticipantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_DatosParticipantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jL_NCurso.setText("N. Curso:");

        jL_NGrupo.setText("N. Grupo:");

        jL_Alumno.setText("Alumno:");

        jL_Apto.setText("Apto:");

        jC_Apto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_AptoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_DatosParticipantesLayout = new javax.swing.GroupLayout(jP_DatosParticipantes);
        jP_DatosParticipantes.setLayout(jP_DatosParticipantesLayout);
        jP_DatosParticipantesLayout.setHorizontalGroup(
            jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosParticipantesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_DatosParticipantesLayout.createSequentialGroup()
                            .addComponent(jL_NCurso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_NCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP_DatosParticipantesLayout.createSequentialGroup()
                            .addComponent(jL_NGrupo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_NGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(jP_DatosParticipantesLayout.createSequentialGroup()
                        .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Alumno)
                            .addComponent(jL_Apto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC_Apto)
                            .addComponent(jT_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jP_DatosParticipantesLayout.setVerticalGroup(
            jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosParticipantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_NCurso)
                    .addComponent(jT_NCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_NGrupo)
                    .addComponent(jT_NGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Alumno)
                    .addComponent(jT_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_DatosParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Apto)
                    .addComponent(jC_Apto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_OpcionesParticipantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        Btn_InsertParticipantes.setForeground(new java.awt.Color(0, 128, 0));
        Btn_InsertParticipantes.setText("Insertar");

        Btn_ModificarParticipantes.setForeground(new java.awt.Color(0, 0, 255));
        Btn_ModificarParticipantes.setText("Modificar");

        Btn_EliminarParticipantes.setForeground(new java.awt.Color(255, 0, 0));
        Btn_EliminarParticipantes.setText("Eliminar");
        Btn_EliminarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarParticipantesActionPerformed(evt);
            }
        });

        Btn_BuscarParticipantes.setForeground(new java.awt.Color(255, 128, 0));
        Btn_BuscarParticipantes.setText("Buscar");

        Btn_MenuParticipantes.setForeground(new java.awt.Color(255, 255, 0));
        Btn_MenuParticipantes.setText("Menu");
        Btn_MenuParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuParticipantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_OpcionesParticipantesLayout = new javax.swing.GroupLayout(jP_OpcionesParticipantes);
        jP_OpcionesParticipantes.setLayout(jP_OpcionesParticipantesLayout);
        jP_OpcionesParticipantesLayout.setHorizontalGroup(
            jP_OpcionesParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcionesParticipantesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jP_OpcionesParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_ModificarParticipantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_OpcionesParticipantesLayout.createSequentialGroup()
                        .addGroup(jP_OpcionesParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_MenuParticipantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_BuscarParticipantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_InsertParticipantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_EliminarParticipantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(27, 27, 27))
        );
        jP_OpcionesParticipantesLayout.setVerticalGroup(
            jP_OpcionesParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_OpcionesParticipantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_InsertParticipantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_ModificarParticipantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_EliminarParticipantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_BuscarParticipantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_MenuParticipantes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_DetallesParticipantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        jTablaParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "N. Curso", "N. Grupo", "Alumno", "Apto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaParticipantes);
        if (jTablaParticipantes.getColumnModel().getColumnCount() > 0) {
            jTablaParticipantes.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTablaParticipantes.getColumnModel().getColumn(1).setPreferredWidth(1);
            jTablaParticipantes.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTablaParticipantes.getColumnModel().getColumn(3).setPreferredWidth(1);
        }

        javax.swing.GroupLayout jP_DetallesParticipantesLayout = new javax.swing.GroupLayout(jP_DetallesParticipantes);
        jP_DetallesParticipantes.setLayout(jP_DetallesParticipantesLayout);
        jP_DetallesParticipantesLayout.setHorizontalGroup(
            jP_DetallesParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_DetallesParticipantesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jP_DetallesParticipantesLayout.setVerticalGroup(
            jP_DetallesParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DetallesParticipantesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_DetallesParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_DatosParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jP_OpcionesParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP_OpcionesParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_DatosParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_DetallesParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_EliminarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EliminarParticipantesActionPerformed

    private void jC_AptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_AptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jC_AptoActionPerformed

    private void Btn_MenuParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuParticipantesActionPerformed
        // TODO add your handling code here:
                Menu obj = new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_MenuParticipantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Participantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Participantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Participantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Participantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Participantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BuscarParticipantes;
    private javax.swing.JButton Btn_EliminarParticipantes;
    private javax.swing.JButton Btn_InsertParticipantes;
    private javax.swing.JButton Btn_MenuParticipantes;
    private javax.swing.JButton Btn_ModificarParticipantes;
    private javax.swing.JCheckBox jC_Apto;
    private javax.swing.JLabel jL_Alumno;
    private javax.swing.JLabel jL_Apto;
    private javax.swing.JLabel jL_NCurso;
    private javax.swing.JLabel jL_NGrupo;
    private javax.swing.JPanel jP_DatosParticipantes;
    private javax.swing.JPanel jP_DetallesParticipantes;
    private javax.swing.JPanel jP_OpcionesParticipantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Alumno;
    private javax.swing.JTextField jT_NCurso;
    private javax.swing.JTextField jT_NGrupo;
    private javax.swing.JTable jTablaParticipantes;
    // End of variables declaration//GEN-END:variables
}
