package Views;

/**
 *
 * @author computador
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setTitle(" Gestion Escolar ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_BienvenidoMainMenu = new javax.swing.JLabel();
        jP_SeleccioneUnaOpcion = new javax.swing.JPanel();
        Btn_CursosMain = new javax.swing.JButton();
        Btn_ParticipantesMain = new javax.swing.JButton();
        Btn_AlumnosMain = new javax.swing.JButton();
        Btn_ProfesoresMain = new javax.swing.JButton();
        Btn_GruposMain = new javax.swing.JButton();
        Btn_SalirMainEND = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_BienvenidoMainMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jL_BienvenidoMainMenu.setText("Bienvenido");

        jP_SeleccioneUnaOpcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione una opcion"));

        Btn_CursosMain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_CursosMain.setText("Cursos");
        Btn_CursosMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CursosMainActionPerformed(evt);
            }
        });

        Btn_ParticipantesMain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_ParticipantesMain.setText("Participantes");
        Btn_ParticipantesMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ParticipantesMainActionPerformed(evt);
            }
        });

        Btn_AlumnosMain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_AlumnosMain.setText("Alumnos");
        Btn_AlumnosMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AlumnosMainActionPerformed(evt);
            }
        });

        Btn_ProfesoresMain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_ProfesoresMain.setText("Profesores");
        Btn_ProfesoresMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProfesoresMainActionPerformed(evt);
            }
        });

        Btn_GruposMain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_GruposMain.setText("Grupos");
        Btn_GruposMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GruposMainActionPerformed(evt);
            }
        });

        Btn_SalirMainEND.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_SalirMainEND.setForeground(new java.awt.Color(255, 0, 0));
        Btn_SalirMainEND.setText("Salir");
        Btn_SalirMainEND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirMainENDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_SeleccioneUnaOpcionLayout = new javax.swing.GroupLayout(jP_SeleccioneUnaOpcion);
        jP_SeleccioneUnaOpcion.setLayout(jP_SeleccioneUnaOpcionLayout);
        jP_SeleccioneUnaOpcionLayout.setHorizontalGroup(
            jP_SeleccioneUnaOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SeleccioneUnaOpcionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jP_SeleccioneUnaOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Btn_GruposMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_ProfesoresMain, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jP_SeleccioneUnaOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_CursosMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ParticipantesMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jP_SeleccioneUnaOpcionLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(Btn_AlumnosMain, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_SalirMainEND))
        );
        jP_SeleccioneUnaOpcionLayout.setVerticalGroup(
            jP_SeleccioneUnaOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SeleccioneUnaOpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_SeleccioneUnaOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_CursosMain, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ProfesoresMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jP_SeleccioneUnaOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_ParticipantesMain, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_GruposMain, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SeleccioneUnaOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_SeleccioneUnaOpcionLayout.createSequentialGroup()
                        .addComponent(Btn_AlumnosMain, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_SeleccioneUnaOpcionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btn_SalirMainEND))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_BienvenidoMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_SeleccioneUnaOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_BienvenidoMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_SeleccioneUnaOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CursosMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CursosMainActionPerformed
        // TODO add your handling code here:
         JF_Cursos obj = new JF_Cursos();
        obj.setVisible(true);
        dispose();        
    }//GEN-LAST:event_Btn_CursosMainActionPerformed

    private void Btn_ParticipantesMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ParticipantesMainActionPerformed
        // TODO add your handling code here:
         JF_Participantes obj = new JF_Participantes();
        obj.setVisible(true);
        dispose();        
    }//GEN-LAST:event_Btn_ParticipantesMainActionPerformed

    private void Btn_AlumnosMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AlumnosMainActionPerformed
        // TODO add your handling code here:
         JF_Alumnos obj = new JF_Alumnos();
        obj.setVisible(true);
        dispose();        
    }//GEN-LAST:event_Btn_AlumnosMainActionPerformed

    private void Btn_GruposMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GruposMainActionPerformed
        // TODO add your handling code here:
          JF_Grupos obj = new JF_Grupos();
        obj.setVisible(true);
        dispose();       
    }//GEN-LAST:event_Btn_GruposMainActionPerformed

    private void Btn_ProfesoresMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProfesoresMainActionPerformed
        // TODO add your handling code here:
           JF_Profesores obj = new JF_Profesores();
        obj.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_Btn_ProfesoresMainActionPerformed

    private void Btn_SalirMainENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirMainENDActionPerformed
        // TODO add your handling code here:
          dispose(); 
    System.exit(0);
    }//GEN-LAST:event_Btn_SalirMainENDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AlumnosMain;
    private javax.swing.JButton Btn_CursosMain;
    private javax.swing.JButton Btn_GruposMain;
    private javax.swing.JButton Btn_ParticipantesMain;
    private javax.swing.JButton Btn_ProfesoresMain;
    private javax.swing.JButton Btn_SalirMainEND;
    private javax.swing.JLabel jL_BienvenidoMainMenu;
    private javax.swing.JPanel jP_SeleccioneUnaOpcion;
    // End of variables declaration//GEN-END:variables
}
